require "pm_finance_constants"

function data()
	return {
		en = {
            [TRANSPORT_TYPE_ROAD] = ("Road transport"),
            [TRANSPORT_TYPE_TRAM] = ("Tram transport"),
            [TRANSPORT_TYPE_RAIL] = ("Railroad transport"),
            [TRANSPORT_TYPE_WATER] = ("Water transport"),
            [TRANSPORT_TYPE_AIR] = ("Air transport"),
            [TRANSPORT_TYPE_ALL] = ("All transport"),
            [CAT_TOTAL] = ("Total"),
            [CAT_INCOME] = ("Income"),
            [CAT_MAINTENANCE] = ("Maintenance"),
            [CAT_MAINTENANCE_VEHICLES] = ("Vehicles"),
            [CAT_MAINTENANCE_INFRASTRUCTURE] = ("Infrastructure"),
            [CAT_INVESTMENTS] = ("Investments"),
            [CAT_INVESTMENTS_VEHICLES] = ("Vehicles"),
            [CAT_INVESTMENTS_TRACKS] = ("Railways"),
            [CAT_INVESTMENTS_ROADS] = ("Roads"),
            [CAT_INVESTMENTS_INFRASTRUCTURE] = ("Infrastructure"),
            [CAT_CASHFLOW] = ("Cashflow"),
            [CAT_PROFIT] = ("Profit"),
            [CAT_LOAN] = ("Loan"),
            [CAT_INTERESTS] = ("Interests"),
            [CAT_BALANCE] = ("Balance"),
            ["#Tooltip.Details.Income"] = ("Your Income"),
			["#Tooltip.Details.Maintenance"] = ("Total Maintenance incl. buildings and vehicles"),
			["#Tooltip.Details.Vehicles"] = ("Acquisition of new vehicles"),
			["#Tooltip.Details.Infrastructure"] = ("Construction of new buildings"),
			["#Tooltip.Details.Taxes.Income"] = ("Taxes or Subsidies on Income"),
			["#Tooltip.Details.Taxes.Vehicles"] = ("Taxes on Vehicle acquisitions"),
			["#Tooltip.Details.Taxes.Infrastructure"]=("Taxes on new constructions"),
			["Parameter.Tooltip"] = ("Choose the number of years to be displayed in the financial overview table."),
		},
		cs_CZ = {
            [TRANSPORT_TYPE_ROAD] = ("Silniční doprava"),
            [TRANSPORT_TYPE_TRAM] = ("Tramvajová doprava"),
            [TRANSPORT_TYPE_RAIL] = ("Železniční doprava"),
            [TRANSPORT_TYPE_WATER] = ("Lodní doprava"),
            [TRANSPORT_TYPE_AIR] = ("Letecká doprava"),
            [TRANSPORT_TYPE_ALL] = ("Veškerá doprava"),
            [CAT_TOTAL] = ("Celkem"),
            [CAT_INCOME] = ("Příjem"),
            [CAT_MAINTENANCE] = ("Údržba"),
            [CAT_MAINTENANCE_VEHICLES] = ("Vozidla"),
            [CAT_MAINTENANCE_INFRASTRUCTURE] = ("Infrastruktura"),
            [CAT_INVESTMENTS] = ("Investice"),
            [CAT_INVESTMENTS_VEHICLES] = ("Vozidla"),
            [CAT_INVESTMENTS_TRACKS] = ("Železnice"),
            [CAT_INVESTMENTS_ROADS] = ("Silnice"),
            [CAT_INVESTMENTS_INFRASTRUCTURE] = ("Infrastruktura"),
            [CAT_CASHFLOW] = ("Provozní zisk "),
            [CAT_PROFIT] = ("Zisk"),
            [CAT_LOAN] = ("Půjčka"),
            [CAT_INTERESTS] = ("Úroky"),
            [CAT_BALANCE] = ("Zůstatek"),
			["Parameter.Label"] = ("Počet roků v přehledu"),
			["Parameter.Tooltip"] = ("Vyberte počet roků, které se mají zobrazit v tabulce finančního přehledu."),
		}
	}
end