function data()
	return {
		en = {
			["#Tooltip.Details.Income"] = ("Your Income"),
			["#Tooltip.Details.Maintenance"] = ("Total Maintenance incl. buildings and vehicles"),
			["#Tooltip.Details.Vehicles"] = ("Acquisition of new vehicles"),
			["#Tooltip.Details.Infrastructure"] = ("Construction of new buildings"),
			["#Tooltip.Details.Taxes.Income"] = ("Taxes or Subsidies on Income"),
			["#Tooltip.Details.Taxes.Vehicles"] = ("Taxes on Vehicle acquisitions"),
			["#Tooltip.Details.Taxes.Infrastructure"]=("Taxes on new constructions"),
			["Income"]=("Income"),
			["Maintenance"]=("Maintenance"),
			["Infrastructure"]=("Infrastructure"),
			["Vehicles"]=("Vehicles"),
			["rail"] = ("Railway"),
			["road"] = ("Road"),
			["tram"] = ("Tram"),
			["air"] = ("Aviation"),
			["water"] = ("Ship doprava"),
			["FinanceTabOverviewLabel"] = ("Finance - Overview"),
			["Total"] = ("Total"),
		},
		cs_CZ = {
			["#Tooltip.Details.Income"] = ("Your Income"),
			["#Tooltip.Details.Maintenance"] = ("Total Maintenance incl. buildings and vehicles"),
			["#Tooltip.Details.Vehicles"] = ("Acquisition of new vehicles"),
			["#Tooltip.Details.Infrastructure"] = ("Construction of new buildings"),
			["#Tooltip.Details.Taxes.Income"] = ("Taxes or Subsidies on Income"),
			["#Tooltip.Details.Taxes.Vehicles"] = ("Taxes on Vehicle acquisitions"),
			["#Tooltip.Details.Taxes.Infrastructure"]=("Taxes on new constructions"),
			["FinanceTabOverviewLabel"] = ("Finance - Přehled"),
			["rail"] = ("Železniční doprava"),
			["road"] = ("Silniční doprava"),
			["tram"] = ("Tramvajová doprava"),
			["air"] = ("Letecká doprava"),
			["water"] = ("Lodní doprava"),
			["Income"]=("Příjem"),
			["Maintenance"]=("Údržba"),
			["Profit"]=("Provozní zisk"),
			["Investments"]=("Investice"),
			["Infrastructure"]=("Infrastruktura"),
			["Vehicles"] = ("Vozidla"),
			["Acquisiton"] = ("Nákup vozidel"),
			["Total"] = ("Celkem"),
			["Cashflow"] = ("Celkem"),
		}
	}
end