function data()
	return {
		en ={
			["#TaxesDescription"]=("This Tab displays an alternate Journal displaying figures per vehicle category and grouped by Investment related and Income related numbers.\nFirst Column displays the actual result, second column displays the taxes that will be charged.\nTaxes will be payed on the first day of the next year.\nClick on Settings to adjust the parameters of this mod."),
			["#Tooltip.Details.Income"] = ("Your Income"),
			["#Tooltip.Details.Maintenance"] = ("Total Maintenance incl. buildings and vehicles"),
			["#Tooltip.Details.Vehicles"] = ("Acquisition of new vehicles"),
			["#Tooltip.Details.Infrastructure"] = ("Construction of new buildings"),
			["#Tooltip.Details.Taxes.Income"] = ("Taxes or Subsidies on Income"),
			["#Tooltip.Details.Taxes.Vehicles"] = ("Taxes on Vehicle acquisitions"),
			["#Tooltip.Details.Taxes.Infrastructure"]=("Taxes on new constructions"),
			["Income"]=("Income"),
			["Maintenance"]=("Maintenance"),
			["Infrastructure"]=("Infrastructure"),
			["Vehicles"]=("Vehicles"),
			["rail"] = ("Railway"),
			["road"] = ("Road"),
			["tram"] = ("Tram"),
			["air"] = ("Aviation"),
			["water"] = ("Ship doprava"),
			["FinanceTabOverviewLabel"] = ("Finance - Overview"),
			["Total"] = ("Total"),
		},
		cs_CZ = {
			["#TaxesDescription"]=("This Tab displays an alternate Journal displaying figures per vehicle category and grouped by Investment related and Income related numbers.\nFirst Column displays the actual result, second column displays the taxes that will be charged.\nTaxes will be payed on the first day of the next year.\nClick on Settings to adjust the parameters of this mod."),
			["#Tooltip.Details.Income"] = ("Your Income"),
			["#Tooltip.Details.Maintenance"] = ("Total Maintenance incl. buildings and vehicles"),
			["#Tooltip.Details.Vehicles"] = ("Acquisition of new vehicles"),
			["#Tooltip.Details.Infrastructure"] = ("Construction of new buildings"),
			["#Tooltip.Details.Taxes.Income"] = ("Taxes or Subsidies on Income"),
			["#Tooltip.Details.Taxes.Vehicles"] = ("Taxes on Vehicle acquisitions"),
			["#Tooltip.Details.Taxes.Infrastructure"]=("Taxes on new constructions"),
			["Income"]=("Příjem"),
			["Maintenance"]=("Údržba"),
			["Infrastructure"]=("Infrastruktura"),
			["Vehicles"] = ("Vozidla"),
			["rail"] = ("Železniční doprava"),
			["road"] = ("Silniční doprava"),
			["tram"] = ("Tramvajová doprava"),
			["air"] = ("Letecká doprava"),
			["water"] = ("Lodní doprava"),
			["FinanceTabOverviewLabel"] = ("Finance - Přehled"),
			["Total"] = ("Celkem"),
		}
	}
end