TRANSPORT_TYPE_ROAD = "Transport.Road"
TRANSPORT_TYPE_TRAM = "Transport.Tram"
TRANSPORT_TYPE_RAIL = "Transport.Rail"
TRANSPORT_TYPE_WATER = "Transport.Water"
TRANSPORT_TYPE_AIR = "Transport.Air"
TRANSPORT_TYPE_ALL = "Transport.All"

CAT_TOTAL = "Cat.Total"
CAT_INCOME = "Cat.Income"
CAT_MAINTENANCE = "Cat.Maintenance"
CAT_MAINTENANCE_VEHICLES = "Cat.Maintenance.Vehicles"
CAT_MAINTENANCE_INFRASTRUCTURE = "Cat.Maintenance.Infrastructure"
CAT_INVESTMENTS = "Cat.Investments"
CAT_INVESTMENTS_VEHICLES = "Cat.Investments.Vehicles"
CAT_INVESTMENTS_TRACKS = "Cat.Investments.Tracks"
CAT_INVESTMENTS_ROADS = "Cat.Investments.Roads"
CAT_INVESTMENTS_INFRASTRUCTURE = "Cat.Investments.Infrastructure"
CAT_CASHFLOW = "Cat.Cashflow"
CAT_PROFIT = "Cat.Profit"
CAT_LOAN = "Cat.Loan"
CAT_INTEREST = "Cat.Interest"
CAT_OTHER = "Cat.Other"
CAT_BALANCE = "Cat.Balance"

COLUMN_LABEL = "Column.Label"
COLUMN_YEAR = "Column.Year"
COLUMN_TOTAL = "Column.Total"

TRANSPORT_TYPES =
{ 
    TRANSPORT_TYPE_ROAD,
    TRANSPORT_TYPE_TRAM,
    TRANSPORT_TYPE_RAIL,
    TRANSPORT_TYPE_WATER,
    TRANSPORT_TYPE_AIR,
    TRANSPORT_TYPE_ALL
}

TRANSPORT_CATEGORIES_LEVEL1 =
{
    CAT_INCOME,
    CAT_MAINTENANCE,
    CAT_INVESTMENTS
}

TRANSPORT_CATEGORIES_LEVEL2 =
{
    [CAT_INCOME] = {},
    [CAT_MAINTENANCE] = { CAT_MAINTENANCE_VEHICLES, CAT_MAINTENANCE_INFRASTRUCTURE },
    [CAT_INVESTMENTS] = { CAT_INVESTMENTS_VEHICLES, CAT_INVESTMENTS_INFRASTRUCTURE, CAT_INVESTMENTS_TRACKS, CAT_INVESTMENTS_ROADS }
}

NUMBER_OF_YEARS_COLUMNS = 5

STYLE_BUTTON = "style-button"
STYLE_TABLE_CELL = "style-table-cell"
STYLE_TABLE_HEADER = "style-table-header"

STYLE_TEXT_LEFT = "style-text-left"
STYLE_TEXT_RIGHT = "style-text-right"

STYLE_LEVEL_0 = "style-level-0"
STYLE_LEVEL_1 = "style-level-1"
STYLE_LEVEL_2 = "style-level-2"
STYLE_LEVEL_PADDING = "style-level-padding"

STYLE_SUMMARY_LABEL = "style-summary-label"
STYLE_SUMMARY_TABLE = "style-summary-table"

TOOLTIP = "Tooltip"
TOOLTIP_GAMEINFO = "Tooltip.GameInfo"
