TRANSPORT_TYPE_ROAD = "road"
TRANSPORT_TYPE_TRAM = "tram"
TRANSPORT_TYPE_RAIL = "rail"
TRANSPORT_TYPE_WATER = "water"
TRANSPORT_TYPE_AIR = "air"
TRANSPORT_TYPE_ALL = "all"

CAT_TOTAL = "total"
CAT_INCOME = "income"
CAT_MAINTENANCE = "maintenance"
CAT_MAINTENANCE_VEHICLES = "maintenance_vehicles"
CAT_MAINTENANCE_INFRASTRUCTURE = "maintenance_infrastructure"
CAT_INVESTMENTS = "investments"
CAT_INVESTMENTS_VEHICLES = "investments_vehicles"
CAT_INVESTMENTS_TRACKS = "investments_tracks"
CAT_INVESTMENTS_ROADS = "investments_roads"
CAT_INVESTMENTS_INFRASTRUCTURE = "investments_infrastructure"
CAT_CASHFLOW = "cashflow"
CAT_PROFIT = "profit"
CAT_LOAN = "loan"
CAT_INTERESTS = "interest"
CAT_BALANCE = "balance"

COLUMN_YEAR = "year"
COLUMN_TOTAL = "total"