TRANSPORT_TYPE_ROAD = "Transport.Road"
TRANSPORT_TYPE_TRAM = "Transport.Tram"
TRANSPORT_TYPE_RAIL = "Transport.Rail"
TRANSPORT_TYPE_WATER = "Transport.Water"
TRANSPORT_TYPE_AIR = "Transport.Air"
TRANSPORT_TYPE_ALL = "Transport.All"

CAT_TOTAL = "total"
CAT_INCOME = "Income"
CAT_MAINTENANCE = "Maintenance"
CAT_MAINTENANCE_VEHICLES = "Maintenance.Vehicles"
CAT_MAINTENANCE_INFRASTRUCTURE = "Maintenance.Infrastructure"
CAT_INVESTMENTS = "Investments"
CAT_INVESTMENTS_VEHICLES = "Investments.Vehicles"
CAT_INVESTMENTS_TRACKS = "Investments.Tracks"
CAT_INVESTMENTS_ROADS = "Investments.Roads"
CAT_INVESTMENTS_INFRASTRUCTURE = "Investments.Infrastructure"
CAT_CASHFLOW = "Cashflow"
CAT_PROFIT = "profit"
CAT_LOAN = "loan"
CAT_INTERESTS = "interest"
CAT_OTHERS = "Others"
CAT_BALANCE = "balance"

COLUMN_YEAR = "year"
COLUMN_TOTAL = "total"

TRANSPORT_TYPES =
{ 
    TRANSPORT_TYPE_ROAD,
    TRANSPORT_TYPE_TRAM,
    TRANSPORT_TYPE_RAIL,
    TRANSPORT_TYPE_WATER,
    TRANSPORT_TYPE_AIR,
    TRANSPORT_TYPE_ALL
}

TRANSPORT_CATEGORIES_LEVEL1 =
{
    CAT_INCOME,
    CAT_MAINTENANCE,
    CAT_INVESTMENTS
}

TRANSPORT_CATEGORIES_LEVEL2 =
{
    [CAT_INCOME] = {},
    [CAT_MAINTENANCE] = { CAT_MAINTENANCE_VEHICLES, CAT_MAINTENANCE_INFRASTRUCTURE },
    [CAT_INVESTMENTS] = { CAT_INVESTMENTS_VEHICLES, CAT_INVESTMENTS_INFRASTRUCTURE, CAT_INVESTMENTS_TRACKS, CAT_INVESTMENTS_ROADS }
}

NUMBER_OF_YEARS_COLUMNS = 5
